import type { Workflow } from "@/types/workflow";

export function generateAirflowDag(workflow: Workflow): string {
  const { nodes = [], edges = [] } = workflow.dagDefinition || {};
  const dagId = workflow.airflowDagId || `bgp_${workflow.workflowId}`;
  const schedule = workflow.cronExpression || "None";

  // Build dependency map
  const deps: Record<string, string[]> = {};
  for (const edge of edges) {
    if (!deps[edge.target]) deps[edge.target] = [];
    deps[edge.target].push(edge.source);
  }

  let tasks = "";
  for (const node of nodes) {
    const taskId = node.id.replace(/[^a-zA-Z0-9_]/g, "_");
    const data = node.data || {};

    if (node.type === "sync") {
      tasks += `
    ${taskId} = PythonOperator(
        task_id="${taskId}",
        python_callable=trigger_sync_task,
        op_kwargs={"task_id": "${data.syncTaskId || ""}"},
    )
`;
    } else if (node.type === "sql") {
      const sql = (data.sql || "SELECT 1").replace(/"/g, '\\"').replace(/\n/g, "\\n");
      tasks += `
    ${taskId} = PythonOperator(
        task_id="${taskId}",
        python_callable=execute_redshift_sql,
        op_kwargs={"sql": "${sql}"},
    )
`;
    } else if (node.type === "python") {
      const script = (data.script || "pass").replace(/"/g, '\\"').replace(/\n/g, "\\n");
      tasks += `
    ${taskId} = PythonOperator(
        task_id="${taskId}",
        python_callable=run_custom_script,
        op_kwargs={"script": "${script}"},
    )
`;
    }

    if (data.retryCount) {
      tasks += `    ${taskId}.retries = ${data.retryCount}\n`;
    }
    if (data.timeout) {
      tasks += `    ${taskId}.execution_timeout = timedelta(seconds=${data.timeout})\n`;
    }
  }

  // Build dependency lines
  let depLines = "";
  for (const edge of edges) {
    const src = edge.source.replace(/[^a-zA-Z0-9_]/g, "_");
    const tgt = edge.target.replace(/[^a-zA-Z0-9_]/g, "_");
    depLines += `    ${src} >> ${tgt}\n`;
  }

  return `"""Auto-generated by BigData Governance Platform"""
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
import requests

API_BASE = "http://platform-service:3000/api"

def trigger_sync_task(task_id, **kwargs):
    resp = requests.post(f"{API_BASE}/sync/{task_id}/start")
    resp.raise_for_status()

def execute_redshift_sql(sql, **kwargs):
    resp = requests.post(f"{API_BASE}/redshift/execute", json={"sql": sql})
    resp.raise_for_status()

def run_custom_script(script, **kwargs):
    exec(script)

with DAG(
    dag_id="${dagId}",
    schedule_interval=${schedule === "None" ? "None" : `"${schedule}"`},
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["bgp"],
) as dag:
${tasks}
${depLines ? `    # Dependencies\n${depLines}` : ""}`;
}
